---
- name: Delete | import common tasks
  tags:
    - k8s
    - openstack
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | delete bastion host if exists
  tags:
    - k8s
    - openstack
  openstack.cloud.server:
    cloud: "{{ os_cloud }}"
    name: "{{ bastion.name }}"
    state: absent
  when: enable_bastion

- name: Delete | tear down k8s cluster
  tags:
    - k8s
    - openstack
  openstack.cloud.coe_cluster:
    cloud: "{{ os_cloud }}"
    name: "{{ k8s_cluster_name }}"
    cluster_template_id: "{{ k8s_cluster_name }}-template"
    state: absent

- name: Delete | check k8s cluster is deleted
  tags:
    - k8s
    - openstack
  ansible.builtin.command: >-
    openstack --os-cloud={{ os_cloud }} coe cluster show {{ k8s_cluster_name }} -c uuid -f value
  changed_when: false
  register: result
  failed_when: result.rc not in [0, 1]
  until: result.rc != 0
  retries: 60
  delay: 10

- name: Delete | delete cluster template
  tags:
    - k8s
    - openstack
  openstack.cloud.coe_cluster_template:
    cloud: "{{ os_cloud }}"
    coe: kubernetes
    image_id: fcos
    name: "{{ k8s_cluster_name }}-template"
    state: absent
...
