---
- name: Setup | create a project
  openstack.cloud.project:
    cloud: pbos
    state: present
    name: "{{ k8s_cluster_name }}"
    description: "Project for {{ k8s_cluster_name }} cluster"
    enabled: True
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true

- name: Setup | create admin password
  ansible.builtin.set_fact:
    admin_password: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits') }}"

- name: Setup | create member password
  ansible.builtin.set_fact:
    member_password: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits') }}"

- name: Setup | create reader password
  ansible.builtin.set_fact:
    reader_password: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits') }}"

- name: Setup | set k8s_cluster_users list
  ansible.builtin.set_fact:
    k8s_cluster_users:
      - {name: "{{ k8s_cluster_name }}_admin", password: "{{ admin_password }}", role: "admin"}
      - {name: "{{ k8s_cluster_name }}_member", password: "{{ member_password }}", role: "member"}
      - {name: "{{ k8s_cluster_name }}_reader", password: "{{ reader_password }}", role: "reader"}

- name: Setup | delete users for the project if exist
  openstack.cloud.identity_user:
    cloud: pbos
    state: absent
    name: "{{ item.name }}"
  loop: "{{ k8s_cluster_users }}"
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  no_log: true

- name: Setup | create users for the project
  openstack.cloud.identity_user:
    cloud: pbos
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    domain: default
    default_project: "{{ k8s_cluster_name }}"
  loop: "{{ k8s_cluster_users }}"
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  no_log: true

- name: Setup | assign user roles
  openstack.cloud.role_assignment:
    cloud: pbos
    user: "{{ item.name }}"
    role: "{{ item.role }}"
    project: "{{ k8s_cluster_name }}"
  loop: "{{ k8s_cluster_users }}"
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  no_log: true

- name: Setup | create cluster openrc files
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.name }}"
    mode: "0600"
  loop: "{{ k8s_cluster.rcfiles }}"

- name: Setup | add project admin credential to clouds.yaml
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.config/openstack/clouds.yaml"
    mode: "0600"
    insertafter: EOF
    marker: "# {mark} {{ k8s_cluster_name }} CREDENTIAL BLOCK"
    block: >2-
        pbos-{{ k8s_cluster_name }}-admin:
          auth:
            auth_url: http://{{ keepalived_vip }}:{{ keystone_port }}/v3
            project_name: {{ k8s_cluster_name }}
            username: {{ k8s_cluster_users | json_query("[?role=='admin'].name") | join('') }}
            password: {{ admin_password }}
            user_domain_name: default
            project_domain_name: default
          region_name: RegionOne
...
